# CI Build runner with Platformio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO Factory images builder

on:
  workflow_dispatch:      # Manual start

# one task per branch/env at a time
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  factory_image:
    runs-on: ubuntu-latest
    if: github.repository == 'vortigont/FireLamp_JeeUI'
    continue-on-error: false
    strategy:
      matrix:
        variant:
          - esp32_4M
          - esp32_4M_debug
#          - esp32S3_4M
#          - esp32S3_4M_debug
#          - esp32S3_16M
#          - esp32S3_16M_debug

    steps:
      - uses: actions/checkout@v4
      - name: PIP Cache
        id: cache-pip
        uses: actions/cache@v4
        env:
          cache-name: cache-pip-pkgs
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{env.cache-name}}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Platformio Cache
        id: cache-pio
        uses: actions/cache@v4
        env:
          cache-name: cache-pio-pkgs
        with:
          path: |
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{env.cache-name}}
          restore-keys: |
            ${{ runner.os }}-pio-
            ${{ runner.os }}-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          #platformio pkg update
      - name: Run PlatformIO build
        run: |
          platformio run -e ${{ matrix.variant }}
      - name: Collect build images
        run: |
          mkdir ~/artifacts
          find ~/ -name 'factory.*.bin'
          find .pio/build/ -name "factory.*.bin" -exec mv -t ~/artifacts/ {} +
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: factory_images
          path: ~/artifacts/*
          compression-level: 9 # maximum compression
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
