# workdir
# /home/runner/work/FireLamp_JeeUI/FireLamp_JeeUI


name: GitHub release creator pipeline

on:
  workflow_dispatch:      # Manual start
#  push:
#    branches: [ master ]
#    tags:
#      - "v*.*.*"

jobs:
  PublishRelease:
    runs-on: ubuntu-latest
    if: github.repository == 'vortigont/FireLamp_JeeUI'
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: PIP Cache
        id: cache-pip
        uses: actions/cache@v4
        env:
          cache-name: cache-pip-pkgs
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{env.cache-name}}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Platformio Cache
        id: pio-pp
        uses: actions/cache@v4
        env:
          cache-name: cache-pio-pkgs
        with:
          path: |
            ~/.platformio/platforms
            ~/.platformio/packages
          key: ${{ runner.os }}-pio-${{env.cache-name}}
          restore-keys: |
            ${{ runner.os }}-pio-
#           Linux-pio-cache-pio-pkgs, Linux-pio-, Linux-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          platformio run -t buildfs
          #platformio pkg update
      - name: Run PlatformIO build
        run: |
          platformio run -e esp32_4M
#         platformio run -e esp32_4M -e esp32_16M -e esp32S3_4M -e esp32S3_16M
#         platformio run -e ${{ matrix.variant }}
      - name: Collect firmware images
        id: prepare_bins
        shell: bash
        run: |
          mkdir ~/artifacts
          pwd
          #find ~/ -name 'factory.*.bin'
          #find ~/ -name 'firmware.*.bin'
          find .pio/build/ -name "factory.*.bin" -exec mv -t ~/artifacts/{}_${{ github.ref_name }} {} +
          find .pio/build/ -name "firmware.*.bin" -exec mv -t ~/artifacts/{}_${{ github.ref_name }} {} +
          fw_pkg_filename="firmware_${{ github.ref_name }}.zip"
          find ~/artifacts/ -name "firmware*" -print | zip -9 ~/artifacts/$fw_pkg_filename -@
          factory_pkg_filename="factory_${{ github.ref_name }}.zip"
          find ~/artifacts/ -name "firmware*" -print | zip -9 ~/artifacts/$factory_pkg_filename -@
      - name: Upload assets to Release
        uses: xresloader/upload-to-github-release@v1
        with:
          draft: true
          tags: true
          verbose: true
          file: "~/artifacts/*.zip"

